version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./node:/usr/src/node
    command: sh -c "cd node && npm init"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true