version: '3.9'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "50000:50000"
    tty: true
    stdin_open: true